version: '3.8'

services:
  app:
    image: ghcr.io/rafaelgoncalves-bit/cortador:latest
    container_name: cortador
    restart: always

    volumes:
      - .:/app
      - static_volume:/app/static

    ports:
      - "8005:8000"

    command: gunicorn cortador2.wsgi:application --bind 0.0.0.0:8000 --timeout 300

    environment:
      - DEBUG=1

volumes:
  static_volume: