version: '3.8'

services:
  cortador:
    image: ghcr.io/rafaelgoncalves-bit/cortador:latest
    restart: always

    volumes:
      - static_volume:/app/static

    ports:
      - "8005:8000"

    networks:
      - global_network

    command: gunicorn cortador2.wsgi:application --bind 0.0.0.0:8000 --timeout 300

    environment:
      - DEBUG=1

volumes:
  static_volume:

networks:
  global_network:
    external: true
    name: global_network