version: '3.8'

services:
  app:
    build: .
    container_name: cortador
    restart: always

    volumes:
      - .:/app
      - static_volume:/app/static

    ports:
      - "8005:8000"

    command: python manage.py runserver 0.0.0.0:8000

    environment:
      - DEBUG=1

volumes:
  static_volume: